# This is Workflow to deploy Chigüire Bot at Railway

name: Chigüire Bot CI 

# Controls when the workflow 
on:
  pull_request:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node Version LTS/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium

      - name: Install packages
        run: npm install
        
      - name: tsc Build 
        run: npm run build

      - name: Deploy
        run: npx railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
